package rec.isolate.syntax

import rec.isolate.Tag

trait SvgTags {
  lazy val altGlyph            = Tag("altGlyph")
  lazy val altGlyphDef         = Tag("altGlyphDef")
  lazy val altGlyphItem        = Tag("altGlyphItem")
  lazy val animate             = Tag("animate")
  lazy val animateMotion       = Tag("animateMotion")
  lazy val animateTransform    = Tag("animateTransform")
  lazy val circle              = Tag("circle")
  lazy val clipPath            = Tag("clipPath")
  lazy val `color-profile`     = Tag("color-profile")
  lazy val cursor              = Tag("cursor")
  lazy val defs                = Tag("defs")
  lazy val desc                = Tag("desc")
  lazy val ellipse             = Tag("ellipse")
  lazy val feBlend             = Tag("feBlend")
  lazy val feColorMatrix       = Tag("feColorMatrix")
  lazy val feComponentTransfer = Tag("feComponentTransfer")
  lazy val feComposite         = Tag("feComposite")
  lazy val feConvolveMatrix    = Tag("feConvolveMatrix")
  lazy val feDiffuseLighting   = Tag("feDiffuseLighting")
  lazy val feDisplacementMap   = Tag("feDisplacementMap")
  lazy val feDistantLighting   = Tag("feDistantLighting")
  lazy val feFlood             = Tag("feFlood")
  lazy val feFuncA             = Tag("feFuncA")
  lazy val feFuncB             = Tag("feFuncB")
  lazy val feFuncG             = Tag("feFuncG")
  lazy val feFuncR             = Tag("feFuncR")
  lazy val feGaussianBlur      = Tag("feGaussianBlur")
  lazy val feImage             = Tag("feImage")
  lazy val feMerge             = Tag("feMerge")
  lazy val feMergeNode         = Tag("feMergeNode")
  lazy val feMorphology        = Tag("feMorphology")
  lazy val feOffset            = Tag("feOffset")
  lazy val fePointLight        = Tag("fePointLight")
  lazy val feSpecularLighting  = Tag("feSpecularLighting")
  lazy val feSpotlight         = Tag("feSpotlight")
  lazy val feTile              = Tag("feTile")
  lazy val feTurbulance        = Tag("feTurbulance")
  lazy val filter              = Tag("filter")
  lazy val font                = Tag("font")
  lazy val `font-face`         = Tag("font-face")
  lazy val `font-face-format`  = Tag("font-face-format")
  lazy val `font-face-name`    = Tag("font-face-name")
  lazy val `font-face-src`     = Tag("font-face-src")
  lazy val `font-face-uri`     = Tag("font-face-uri")
  lazy val foreignObject       = Tag("foreignObject")
  lazy val g                   = Tag("g")
  lazy val glyph               = Tag("glyph")
  lazy val glyphRef            = Tag("glyphRef")
  lazy val hkern               = Tag("hkern")
  lazy val image               = Tag("image")
  lazy val line                = Tag("line")
  lazy val linearGradient      = Tag("linearGradient")
  lazy val marker              = Tag("marker")
  lazy val mask                = Tag("mask")
  lazy val metadata            = Tag("metadata")
  lazy val `missing-glyph`     = Tag("missing-glyph")
  lazy val mpath               = Tag("mpath")
  lazy val path                = Tag("path")
  lazy val pattern             = Tag("pattern")
  lazy val polygon             = Tag("polygon")
  lazy val polyline            = Tag("polyline")
  lazy val radialGradient      = Tag("radialGradient")
  lazy val rect                = Tag("rect")
  lazy val set                 = Tag("set")
  lazy val stop                = Tag("stop")
  lazy val svg                 = Tag("svg")
  lazy val switch              = Tag("switch")
  lazy val symbol              = Tag("symbol")
  lazy val text                = Tag("text")
  lazy val textPath            = Tag("textPath")
  lazy val tref                = Tag("tref")
  lazy val tspan               = Tag("tspan")
  lazy val use                 = Tag("use")
  lazy val view                = Tag("view")
  lazy val vkern               = Tag("vkern")
}

object Svg extends SvgTags
