package rec.syntax

import rec.Tag

trait Tags {
  // From https://github.com/lihaoyi/scalaTags/blob/master/scalaTags/src/scalaTags/vdom/Tags.scala
  // Root Element
  lazy val html = Tag("html")
  // Document Metadata
  lazy val head = Tag("head")
  lazy val base = Tag("base")
  lazy val link = Tag("link")
  lazy val meta = Tag("meta")
  // Scripting
  lazy val script = Tag("script")
  // Sections
  lazy val body   = Tag("body")
  lazy val h1     = Tag("h1")
  lazy val h2     = Tag("h2")
  lazy val h3     = Tag("h3")
  lazy val h4     = Tag("h4")
  lazy val h5     = Tag("h5")
  lazy val h6     = Tag("h6")
  lazy val header = Tag("header")
  lazy val footer = Tag("footer")
  // Grouping content
  lazy val p          = Tag("p")
  lazy val hr         = Tag("hr")
  lazy val pre        = Tag("pre")
  lazy val blockquote = Tag("blockquote")
  lazy val ol         = Tag("ol")
  lazy val ul         = Tag("ul")
  lazy val li         = Tag("li")
  lazy val dl         = Tag("dl")
  lazy val dt         = Tag("dt")
  lazy val dd         = Tag("dd")
  lazy val figure     = Tag("figure")
  lazy val figcaption = Tag("figcaption")
  lazy val div        = Tag("div")
  // Text-level semantics
  lazy val a      = Tag("a")
  lazy val em     = Tag("em")
  lazy val strong = Tag("strong")
  lazy val small  = Tag("small")
  lazy val s      = Tag("s")
  lazy val cite   = Tag("cite")
  lazy val code   = Tag("code")
  lazy val sub    = Tag("sub")
  lazy val sup    = Tag("sup")
  lazy val i      = Tag("i")
  lazy val b      = Tag("b")
  lazy val u      = Tag("u")
  lazy val span   = Tag("span")
  lazy val br     = Tag("br")
  lazy val wbr    = Tag("wbr")
  // Edits
  lazy val ins = Tag("ins")
  lazy val del = Tag("del")
  // Embedded content
  lazy val img      = Tag("img")
  lazy val iframe   = Tag("iframe")
  lazy val embed    = Tag("embed")
  lazy val `object` = Tag("object")
  lazy val param    = Tag("param")
  lazy val video    = Tag("video")
  lazy val audio    = Tag("audio")
  lazy val source   = Tag("source")
  lazy val track    = Tag("track")
  lazy val canvas   = Tag("canvas")
  lazy val map      = Tag("map")
  lazy val area     = Tag("area")
  // Tabular data
  lazy val table    = Tag("table")
  lazy val caption  = Tag("caption")
  lazy val colgroup = Tag("colgroup")
  lazy val col      = Tag("col")
  lazy val tbody    = Tag("tbody")
  lazy val thead    = Tag("thead")
  lazy val tfoot    = Tag("tfoot")
  lazy val tr       = Tag("tr")
  lazy val td       = Tag("td")
  lazy val th       = Tag("th")
  // Forms
  lazy val form     = Tag("form")
  lazy val fieldset = Tag("fieldset")
  lazy val legend   = Tag("legend")
  lazy val label    = Tag("label")
  lazy val input    = Tag("input")
  lazy val button   = Tag("button")
  lazy val select   = Tag("select")
  lazy val datalist = Tag("datalist")
  lazy val optgroup = Tag("optgroup")
  lazy val option   = Tag("option")
  lazy val textarea = Tag("textarea")

  lazy val section = Tag("section")
  lazy val nav     = Tag("nav")
  lazy val article = Tag("article")
  lazy val aside   = Tag("aside")
  lazy val address = Tag("address")
  lazy val menu    = Tag("menu")
}
