package rec.syntax

import rec.{Attr, Html, NodeList, ReadList}
import rec.Html._

trait Tags {
  private type HtmlMaker[R] =
    (Seq[Attr], ReadList[R], NodeList[R]) => Html[R]
  private def mkTag[R](str: String): HtmlMaker[R] =
    Element[R](str, _, _, _)

  // From https://github.com/lihaoyi/scalatags/blob/master/scalatags/src/scalatags/vdom/Tags.scala
  def html[R]       = mkTag[R]("html")
  def head[R]       = mkTag[R]("head")
  def base[R]       = mkTag[R]("base")
  def link[R]       = mkTag[R]("link")
  def meta[R]       = mkTag[R]("meta")
  def script[R]     = mkTag[R]("script")
  def body[R]       = mkTag[R]("body")
  def h1[R]         = mkTag[R]("h1")
  def h2[R]         = mkTag[R]("h2")
  def h3[R]         = mkTag[R]("h3")
  def h4[R]         = mkTag[R]("h4")
  def h5[R]         = mkTag[R]("h5")
  def h6[R]         = mkTag[R]("h6")
  def header[R]     = mkTag[R]("header")
  def footer[R]     = mkTag[R]("footer")
  def p[R]          = mkTag[R]("p")
  def hr[R]         = mkTag[R]("hr")
  def pre[R]        = mkTag[R]("pre")
  def blockquote[R] = mkTag[R]("blockquote")
  def ol[R]         = mkTag[R]("ol")
  def ul[R]         = mkTag[R]("ul")
  def li[R]         = mkTag[R]("li")
  def dl[R]         = mkTag[R]("dl")
  def dt[R]         = mkTag[R]("dt")
  def dd[R]         = mkTag[R]("dd")
  def figure[R]     = mkTag[R]("figure")
  def figcaption[R] = mkTag[R]("figcaption")
  def div[R]        = mkTag[R]("div")
  def a[R]          = mkTag[R]("a")
  def em[R]         = mkTag[R]("em")
  def strong[R]     = mkTag[R]("strong")
  def small[R]      = mkTag[R]("small")
  def s[R]          = mkTag[R]("s")
  def cite[R]       = mkTag[R]("cite")
  def code[R]       = mkTag[R]("code")
  def sub[R]        = mkTag[R]("sub")
  def sup[R]        = mkTag[R]("sup")
  def i[R]          = mkTag[R]("i")
  def b[R]          = mkTag[R]("b")
  def u[R]          = mkTag[R]("u")
  def span[R]       = mkTag[R]("span")
  def br[R]         = mkTag[R]("br")
  def wbr[R]        = mkTag[R]("wbr")
  def ins[R]        = mkTag[R]("ins")
  def del[R]        = mkTag[R]("del")
  def img[R]        = mkTag[R]("img")
  def iframe[R]     = mkTag[R]("iframe")
  def embed[R]      = mkTag[R]("embed")
  def `object`[R]   = mkTag[R]("object")
  def param[R]      = mkTag[R]("param")
  def video[R]      = mkTag[R]("video")
  def audio[R]      = mkTag[R]("audio")
  def source[R]     = mkTag[R]("source")
  def track[R]      = mkTag[R]("track")
  def canvas[R]     = mkTag[R]("canvas")
  def map[R]        = mkTag[R]("map")
  def area[R]       = mkTag[R]("area")
  def table[R]      = mkTag[R]("table")
  def caption[R]    = mkTag[R]("caption")
  def colgroup[R]   = mkTag[R]("colgroup")
  def col[R]        = mkTag[R]("col")
  def tbody[R]      = mkTag[R]("tbody")
  def thead[R]      = mkTag[R]("thead")
  def tfoot[R]      = mkTag[R]("tfoot")
  def tr[R]         = mkTag[R]("tr")
  def td[R]         = mkTag[R]("td")
  def th[R]         = mkTag[R]("th")
  def form[R]       = mkTag[R]("form")
  def fieldset[R]   = mkTag[R]("fieldset")
  def legend[R]     = mkTag[R]("legend")
  def label[R]      = mkTag[R]("label")
  def input[R]      = mkTag[R]("input")
  def button[R]     = mkTag[R]("button")
  def select[R]     = mkTag[R]("select")
  def datalist[R]   = mkTag[R]("datalist")
  def optgroup[R]   = mkTag[R]("optgroup")
  def option[R]     = mkTag[R]("option")
  def textarea[R]   = mkTag[R]("textarea")
  def section[R]    = mkTag[R]("section")
  def nav[R]        = mkTag[R]("nav")
  def article[R]    = mkTag[R]("article")
  def aside[R]      = mkTag[R]("aside")
  def address[R]    = mkTag[R]("address")
  def menu[R]       = mkTag[R]("menu")
}
